thelsing/knx

address_table_object.cpp
application_program_object.cpp
association_table_object.cpp
bau57B0.cpp
device_object.cpp
group_object_table_object.cpp
interface_object.cpp
interface_object.h
ip_parameter_object.cpp
table_object.cpp

Hi!
Please consider merging this pull request.

Improve property description handling

---

src/knx/data_link_layer.cpp
src/knx/data_link_layer.h
src/knx/ip_data_link_layer.cpp
src/knx/tpuart_data_link_layer.cpp
src/knx/tpuart_data_link_layer.h

- split frame tx and confirm rx in an async manner
- add frame byte timeout
- add tx confirm timeout
- add crc check

async tpuart_data_link_layer version

---

examples/knx-demo/knx-demo.ino
src/esp32_platform.cpp
src/esp32_platform.h
src/knx/bits.h
src/knx_facade.cpp
src/knx_facade.h

This code adds support for the ESP32 platform. It's very similar to ESP8266 but needed some changes in the multicast code.

added ESP32 platform

---

.travis.yml
examples/knx-usb/.vscode/extensions.json
examples/knx-usb/custom_hwids.py
examples/knx-usb/platformio-ci.ini
examples/knx-usb/platformio.ini
src/knx/config.h
src/knx/ip_parameter_object.cpp

Changed Travis setup to use matrix for each build:
* linux platform (cpp)
* arduino platform (cpp)
* platformio projects (python-2.7)
So I have removed the global env var "MODE" and put everything into its own matrix build entry.
This was needed as I had to include "language" also inside the build matrix.

Travis knx usb

---

.travis.yml
examples/knx-usb/platformio-ci.ini

This fixes the Arduino and the PlatformIO builds with Travis CI.
The Linux build still does not build, because of some "ugly" debug code. ;)

Fix travis build

---

examples/knx-sonoffS20/knx-sonoffS20.ino

Change the datapoints types to 1.1, 1.2 or 1.3 to match the requirements (no dpt *.0) in dpt.cpp

Datapoints ending in .0 are invalid

---

src/knx/bau07B0.cpp
src/knx/tpuart_data_link_layer.cpp

~~This is supposed to fix #83~~
Only add warning message.

Add warning message in TP-UART data link layer

---

src/knx_facade.h

* set saveSize at compile time
* make sure USERDATA_SAVE_SIZE is set to valid value

fix userdata saverestore (#133)

---

src/knx/device_object.h

so that it behaves like a new KNX device

Change individual address to 15.15.255

---

src/knx/ip_parameter_object.cpp

fix wrong IP

---

src/knx/dptconvert.cpp

Somehow in dpt convert code is doubled. This PR removes the doubled code.

Double code removal

---

src/knx_facade.h

Please find here 2 new methods to get parameters;
- paramSignedByte to use singed byte parameter values
- paramBit to use boolean parameter values

Add 2 new methods: paramSignedByte and paramBit. Comments and usage inside code

---

examples/knx-linux-coupler/fdsk.cpp
examples/knx-linux/fdsk.cpp
src/knx/association_table_object.cpp
src/knx/bau_systemB.cpp
src/knx/dptconvert.cpp

Hi thelsing,
maybe you should activate LGTM and codefactor apps for better code quality.

fix constant comparison

---

src/knx/dptconvert.cpp

Added Datapointconversion for Datapointtype 7.600 (colortemperature)

Added Datapointtype DPT 7.600 (colortemperature)

---

README.md
src/knx_facade.h

- Add callback functions for indicating prog mode
- Allow to set LED_BUILTIN to another value
- Improved documentation
@thelsing Thank you for providing this library!

Add callback functions for prog mode and improve documentation

---

src/rp2040_arduino_platform.cpp

get the unique id directly from flash instead using the async. SDK call.

solves #183

---

src/knx/group_object.cpp

Sorry for my stupidity, but I forgot the correct initialization with PR #187. This ist the correction-PR.

Forgotten init for PR #187

---

src/cc1310_platform.h
src/knx/address_table_object.h
src/knx/bau07B0.h
src/knx/bau091A.h
src/knx/bau27B0.h
src/knx/bau2920.h
src/knx/bau57B0.h
src/knx/bau_systemB_coupler.h
src/knx/bau_systemB_device.h
src/knx/callback_property.h
src/knx/data_property.h
src/knx/function_property.h
src/knx/interface_object.h
src/knx/ip_data_link_layer.h
src/knx/network_layer_coupler.h
src/knx/network_layer_device.h
src/knx/rf_data_link_layer.h
src/knx/rf_physical_layer_cc1310.h
src/knx/router_object.h
src/knx/secure_application_layer.h
src/knx/security_interface_object.h
src/knx/tpuart_data_link_layer.h

Hi thelsing,
it has no effect on the firmware, the compiled firmware is identical.

Removed redundant declaration

---

.github/workflows/cmake-arm.yml
.github/workflows/cmake-native.yml
.github/workflows/codeql-analysis.yml
src/knx/application_layer.cpp
src/knx/application_layer.h
src/knx/bau_systemB_coupler.cpp
src/knx/device_object.cpp
src/knx/dptconvert.cpp
src/knx/interface_object.h
src/knx/knx_ip_frame.h
src/knx/knx_value.h
src/knx/memory.cpp
src/knx/rf_physical_layer_cc1101.cpp
src/knx/secure_application_layer.h
src/knx/security_interface_object.cpp
src/knx/tpuart_data_link_layer.cpp
src/knx/transport_layer.cpp
src/knx/usb_tunnel_interface.cpp

Hi thelsing, now should be all Style issues fixed.

Fix last CodeFactor Style issues

---

.vscode/extensions.json
src/cc1310_platform.cpp
src/cc1310_platform.h
src/esp32_platform.cpp
src/esp32_platform.h
src/esp_platform.cpp
src/esp_platform.h
src/knx/platform.cpp
src/knx/platform.h
src/linux_platform.cpp
src/linux_platform.h
src/rp2040_arduino_platform.cpp
src/rp2040_arduino_platform.h
src/samd_platform.cpp
src/samd_platform.h
src/stm32_platform.cpp
src/stm32_platform.h

changed uint8_t getEepromBuffer(uint16_t size) to uint8_t getEepromBuffer(uint32_t size) to allow eeprom > 65k

32bit eeprom size

---

src/samd_platform.cpp

add support for KNX_FLASH_OFFSET on samd

support KNX_FLASH_OFFSET on samd

---

src/knx/bau_systemB.cpp

This PR fixes wrong handling of the FunctionPropertyRead Request.

fix wrong functionPropertyState handling

---

src/knx/association_table_object.cpp

check initialize of AssociationTable

Fix check init of assoc table
