thelsing/knx

src/arduino_platform.cpp
src/arduino_platform.h
src/esp32_platform.cpp
src/esp32_platform.h
src/esp_platform.cpp
src/esp_platform.h
src/knx_facade.cpp
src/samd_platform.cpp
src/samd_platform.h

This code adds a setter _setUart_ and a getter _getUart_ for the HardwareSerial-object of the ArduinoPlatform and adds support for custom UARTs (e.g. Serial1, Serial2). I overloaded the constructor of the ArduinoPlatform-implementations (eg. _esp_platform_) with the possibility to set a specific HardwareSerial-object.

setter/getter & overloaded constructor (ArduinoPlatform) for HardwareSerial-object

---

knx-linux/main.cpp
src/linux_platform.cpp

* added signal handler for CTRL-C and SIGTERM to be able to close and unexport GPIOs
* prevent swapping of the process (inspired by BCM2835 lib)
* GPIO reading/writing of values will now open the GPIO sysfs file and keep it open until process is finished and the GPIOs are unexported (inspired by WiringPi)

Improve GPIO for Linux platform

---

src/knx/application_program_object.cpp
src/knx/bau07B0.cpp
src/knx/bau27B0.cpp
src/knx/bau57B0.cpp
src/knx/bau_systemB.cpp
src/knx/device_object.cpp
src/knx/ip_parameter_object.cpp
src/knx/property.cpp
src/knx/property.h
src/knx/table_object.cpp

startIndex = 0 must return two bytes which contain the size of the property.
PID_IO_LIST: Due to missing explicit casting, the compiler chooses uint8_t variant of overloaded method.

Bugfixes for property startIndex 0 and PID_IO_LIST

---

src/knx/memory.cpp
src/knx/tpuart_data_link_layer.cpp

With an ESP32 + TPUART configuration, I noticed a crash at program startup in the TpUartDataLinkLayer::loop()
It seems that the _sendBuffer can be NULL when used in logic.
I have naively added a logic to avoid this NULL dereference which works at my side, but I am not sure if this is correct with the whole project design, please don't hesitate to comment.
Thanks

Try fixing a crash due to NULL derefence

---

src/knx/rf_physical_layer_cc1310.cpp

Finish RX on cancelled RX_CmdAdv if we issued hard abort due to crc16/address mismatch

Fix CC1310 RX abort

---

examples/knx-cc1310/CC1310_LAUNCHXL_NoRTOS.lds
examples/knx-cc1310/RTT/SEGGER_RTT_Conf.h
examples/knx-cc1310/ccs/.cproject
examples/knx-cc1310/knx_wrapper.cpp

Add nano.specs to linker to reduce memory footprint and increase HEAP+STACK sizes.
Reduce buffer size for Segger RTT UP-Buffer.

Optimize CC1310 memory footprint

---

src/knx/bits.h
src/knx/group_object.h

Addressing: https://github.com/thelsing/knx/issues/109
This is quite useful when using callbacks on group objects. When modelling a device as a class, the callback is typically a non-static member function that cannot be passed as a regular function pointer.
An elegant solution is to combined std::bind with std::function to register a member function of a specific class object.
Implications
The change is simple but including STL headers conflicts with the definition of max and min macros in the arduino framework for SAMD. This should be fixed in arduino/ArduinoCore-samd#399 but not released.
Per interim, `bits.h` is changed to do a conditional 
```
#undef max
#undef min
```

Enabling std::function support for SAMD

---

examples/knx-demo-coupler/platformio-ci.ini
examples/knx-demo/platformio-ci.ini
examples/knx-usb/platformio-ci.ini
src/knx/config.h

(recreating a clean version of https://github.com/thelsing/knx/pull/108)
Having USE_DATASECURE defined by default breaks installations that do not use KNX Secure.
Reason
Due the the way "bool BauSystemBCoupler::configured()" is implemented, "knx.configured()" will always return "false"
Proposed Solution
Let the user define USE_DATASECURE via compiler flags when required.

Fix: "bool BauSystemBCoupler::configured()"

---

src/knx_facade.h

Recent SAMD arduino core has multiple attachInterrupt overloads. Using the enum type PinStatus instead of a generic uint32_t for the _buttonPinIntteruptOn variable addresses this.

Fix ambiguous call to attachInterrupt

---

src/knx/memory.h

The metadata segment in EEPROM/FLASH for storing the application program is not correct. This caused parameters to be written into the metadata segment and vice versa.

Fixing metadata size

---

src/esp32_platform.cpp
src/esp32_platform.h
src/esp_platform.cpp
src/esp_platform.h
src/knx/platform.cpp
src/knx/platform.h
src/knx_facade.h
src/samd_platform.cpp
src/samd_platform.h
src/stm32_platform.cpp
src/stm32_platform.h

* see https://github.com/ricaun/ArduinoUniqueID
* calculated from ESP.getEfuseMac() on ESP32
* ESP.getChipId() on ESP8266
* SERIAL_NUMBER_WORD_0-3 on SAMD
* HAL_GetUIDw0-2() on STM32
* defaults to 0x01020304 on other platforms
So far only tested on ESP32. But SAMD seems to also work. We should try to add support for the other platforms (linux and CC1310).

generate unique serial number (#90)

---

examples/knx-bme680/knx-bme680.ino
src/esp32_platform.cpp
src/knx_facade.h

restore() in knx_facade.h needs to be implemented using const uint8_t* to override save_restore.h as seen here:
https://github.com/thelsing/knx/blob/e57bbf9dbe25505a9f02d83f111d9df7852c18df/src/knx/save_restore.h#L31-L34
Currently the default declaration in save_restore.h is called because knx_facade.h does not override it correctly:
https://github.com/thelsing/knx/blob/e57bbf9dbe25505a9f02d83f111d9df7852c18df/src/knx_facade.h#L354-L360
https://github.com/thelsing/knx/blob/e57bbf9dbe25505a9f02d83f111d9df7852c18df/src/knx_facade.h#L43
https://github.com/thelsing/knx/blob/e57bbf9dbe25505a9f02d83f111d9df7852c18df/src/knx_facade.h#L274-L277
ESP32 EEPROM library:
For ESP32 the EEPROM library checks if data was modified to avoid unnecessary writes to the flash. This is one with a dirty flag …

fix userdata saverestore

---

examples/knx-demo/knx-demo.ino
examples/knx-demo/platformio-ci.ini
examples/knx-demo/platformio.ini

Hi,
the WifiManager is also required for the ESP32.

fix ESP32 IP KNX Demo

---

src/esp32_platform.cpp
src/esp32_platform.h
src/esp_platform.cpp
src/esp_platform.h

#9 added KNX IP discovery support for ESP8266 and ESP32 boards.
Tested with ETS 5.7.4 and an ESP32 Board.

add KNX IP discovery support 

---

src/knx/bits.h
src/knx/group_object.h
src/knx_facade.cpp
src/knx_facade.h
src/rp2040_arduino_platform.cpp
src/rp2040_arduino_platform.h

tested to work with Raspberry Pi Pico, demo sektch is running, programming with ETS works and device is sending knx telegrams

added support for RP2040 (Raspberry Pi Pico)

---

examples/knx-bme680/knx-bme680.ino

Save-/restore callbacks need to be defined before knx.readMemory() to ensure the restore callback is called.

Fix callback sequence

---

src/knx/knx_value.cpp

KNXValue::ulongValue() returns wrong value for type ULongType. This PR fixes this.

Returning correct value for ULongType.

---

src/knx/tpuart_data_link_layer.cpp
src/knx/tpuart_data_link_layer.h

tl;dr: PR implements full duplex in tpuart layer. Stay in loop in time critical handling.
The tpuart-layer is implemented in half duplex with a common state for sending and receiving. This works only with very low bus load and leads to many transmission errors. The tpuart communication is full duplex. While uploading a layer-2 packet to the TPUART it may receive packets from the bus. Also it has to acknowledge the received packet as soon as possible while uploading.
Commit 'TPUART full duplex handling' changes the tpuart-layer to be full duplex. For that it uses two state machines. One for sending and one for receiving. It also recognizes end-of-packet (EOP) gaps. The TPUART signals the end of a packet with such a gap. This must be used to stop processing a layer-2 packet receiption and …

Use full duplex in tpuart_data_link_layer.

---

src/knx/tpuart_data_link_layer.cpp

In the last change an inner loop was introduced. This should stabilize receiving on high load where the loop is called infrequently.
This inner loop spans the receiving and transmitting part. The inclusion of the transmitting part is not good. If a long frame is to be sent it fills the serial tx buffer completely. In this moment writeUart becomes a blocking function, This slows down the loop and leads to false detection of EOP (end of packet) gaps.
A filled tx queue also delays the ACK message. Therefore the tx queue should generally be kept short. To control the length of the tx queue the tx counterpart of uartAvailable() is missing.
Commit 1 fixes false EOP detection by including only the receive part in the loop.
With this fix it may happen (on high load) that a complete echo is …

TPUART: Avoid false EOP

---

src/knx/dpt.h
src/knx/dptconvert.cpp
src/knx/dptconvert.h

The value is delivered as  uint32_t. The colors are identical to RGB with the white channel added in the most sigificant byte. Resulting in WRGB which is identical to the usage in the neopixel library.
The color mask is get/set via type index 1.

Added support for DPT 251.600 RGBW

---

src/knx/dptconvert.cpp

Initial DPT251.600 support delivered the color bytes in WRGB order which seemed useful, but is unexpected.
This commit changes it to the RGBW order according to the KNX data type definition.

DPT251.600 Changed color byte order from WRGB to RGBW (R MSB).

---

src/knx/tpuart_data_link_layer.cpp
src/knx/tpuart_data_link_layer.h

I found some more problems in the tpuart implementation.
**Commit "tx throttle"**: This throttles sending of bytes to the tpuart. This fixes 2 problems. First, when there is no load on the main loop, it is still possible to fill the software tx-buffer of the serial. This leads to blocking calls on uart-write and therefore to a long stay in knx::loop. Second, when the software tx-buffer is full and we need to acknowledge a just received L2-packet, our acknowledge is put at the end of the buffer and is therefore delayed by a certainly long time. Our acknowledge may come to late then.
By throttling the transmission, the software tx-buffer still contains not more than 2-3 bytes.
**Commit "New state RX_L_ADDR; loop load adaption"**: In my former PR I've introduced waiting in knx::loop until …

More tpuart fixes

---

src/knx/tpuart_data_link_layer.cpp

The commands and bits in ACK handling were hard coded. Using defines makes it more readable.

Using defines in ACK handling

---

src/samd_platform.cpp
src/samd_platform.h

Provides folllowing features
- Get rid of EEPROM emulation
- Use SAMD-Flash without copying parameters to RAM
Allows bigger ETS-Applications on the SAMD platform
The new flash handling with 1024 Byte flash size is now the default. Size of flash can be defined with KNX_FLASH_SIZE and must be mutliple of 1024. New implementation is independent of previously used FlashStorage library.
Old behaviour can be reastablished with USE_SAMD_EEPROM_EMULATION.

Reimplement SAMD flash storage based on new memory handling

---

src/knx/tpuart_data_link_layer.cpp
src/knx/tpuart_data_link_layer.h

This PR fixes a problem when the main loop gets stuck. In this moment, if TPUART sends us more data, this fills the serial input buffer.
If this data gets to much we can't process it on the next loop call. This is because time to report back U_ACK_REQ is already over.
Therefore it makes no sense to deal with this old data.
Instead the input buffer is flushed and a new packet start is detected via end of packet gap.

Handling buffer overrun

---

src/knx/group_object.cpp
src/knx/group_object.h

After startup, some knx devices might have uninitialized GroupObjects, because there exists no sensible value for such a GroupObject. This is often the case for logic modules (where the output of a logic might depend on multiple inputs, which did not receive a telegram yet) oder for gateway modules, where the output depends on a value from an other bus system, which did not send a value itself.
A GroupValueRead on sucht an uninitialized GroupObject returned the DPT specific initial value, which might cause wrong actions on the KNX bus. This change prevents GroupValueRead requests for uninitialized GroupObjects. As soon as they get initialized through an external value (GroupValueWrite) or an internal value (GroupObject::value(x)), the behaviour is as before.
This change should have no …

Feature: Uninitialized GO handling

---

src/knx/tpuart_data_link_layer.cpp

This PR removes the artifical tx-state machine state TX_WAIT_ECHO. It was introduced to detect problems in state handling.
Also it fixes the echo detection. Echos are detected by comparing the control byte, the address bytes and another byte. Here the change of the repeat flag is handled. When the complete packet is received, another echo check is done, where the  CRC is compared. If it is different the packet is not seen as an echo. But when the repeat flag is changed, the CRC is different, but it's still an echo. I have removed this test, because it leads to receiption of echos.

Removed unneded TX_WAIT_ECHO state; fixed echo detection

---

src/knx/address_table_object.cpp
src/knx/association_table_object.cpp
src/knx/bau.cpp
src/knx/bau.h
src/knx/bau_systemB.cpp
src/knx/bau_systemB.h
src/knx/group_object_table_object.cpp
src/knx/table_object.cpp
src/knx/table_object.h
src/knx_facade.h

This change adds 2 callbacks:
- beforeRestartCallback, which is called immediately before the module is restarted programmatically (i.e. ResetDevice from ETS or restart after programming). It allows to save application specific data before a restart happens.
- beforeTablesUnloadCallback, which is called directly before the ETS programs the module. It allows to save current GroupObject values, before they get lost as soon als Tables are unloded. 
Usually, a beforeRestartCallback is called after beforeTablesUnload, because ETS restarts a module after a programming procedure.
This change has no sideeffects as long as no callbacks are added by the firmware using this stack.

Feature: additional callbacks for application

---

src/knx/bau_systemB_device.cpp

- GroupObjects use callback infrastructure also during write to bus
- external and internal write of a GO can be handled identically
- needs #define INTERNAL_GROUPOBJECT
Without INTERNAL_GROUPOBJECT the behaviour is not changed. Otherwise the callback, which indicates a GO change is called also as soon as an GO value is sent to the KNX-Bus. In most cases such a behaviour is not necessary. I need it for my generic logicmodule to allow generic connections of Output-GO with Input-GO without sending anything to the KNX bus.
The change is as minimal invasive as I could do...
Regards,
Waldemar

GroupObjects can communicate internally

---

src/esp32_platform.cpp
src/esp_platform.cpp

For the ESP32, you cannot call EEPROM.begin(size) multiple times, and get the same data buffer back. Each call re-creates the in-memory data array mirror of the flash contents. The ESP32 arduino library the code is clearing EEPROM emulation data array is here;
https://github.com/espressif/arduino-esp32/blob/02c3ec01cca90d3b84398791656599d8cb3bb668/libraries/EEPROM/src/EEPROM.cpp#L128
The result is that when loading a program from ETS doesn't work because it calls Esp32Platform::getEepromBuffer() several times (calling EEPROM.begin(size)), causing it for forget all previously changed bytes.
Ideally we should could use the .length() to determine if the EEPROM was initialized properly. 
However this was broken until quite recently https://github.com/espressif/arduino-esp32/pull/5775 …

Esp32Platform reinitializing EEPROM multiple times causing it to forget staged EEPROM changes

---

src/esp32_platform.cpp
src/esp_platform.cpp

This fixes the EEPROM initialization code for the ESP8266/ESP32 platform that got accidentally changed in PR #196 from the size specified by the function argument to the KNX_FLASH_SIZE.

Fixed accidental swap of a parameter in the ESP* platform EEPROM initialization from PR #196

---

examples/knx-demo-diy/knx-demo-diy.ino
src/knx/bau_systemB.cpp
src/knx/bau_systemB.h
src/knx_facade.h

This fixes a null pointer de-reference found in issue #191, where one of the constructors in KnxFacade was accessing the platform pointer without it being initialized, crashing the micro-controller.
Its fixed by also explicitly passing in the platform pointer to the constructor so it can be properly initialized and the KnxFacade::platform() method now always works as expected. An alternative would be to assign a static bau number in the constructor but that would leave the platform pointer uninitialized.

Fix #191 by initializing the platform pointer in all KnxFacade constructors

---

src/knx/bau_systemB_device.cpp

- if go handler writes to same go, value is not sent to bus anymore
This PR fixes an issue introduced with PR #194: If the go handler changes the value of the handled go, the value is not written to KNX bus, even if the T-Flag (German: Ü-Flag) is set. This is because I incorrectly moved `go.commFlag(Updated);` after the call of the go handler. This is corrected now.
IMHO this is a rare, but nevertheless supported case, which should be corrected.
Regards,
Waldemar

FIX issue introduced with #194

---

src/knx/bau_systemB_device.cpp
src/knx/bits.cpp

- happens just with large applications
- occured mainly on SAMD platform
- new crc16ccitt algorithm without additional buffer
- reorder groupObjTable in memory for less fragmentation
Hi @thelsing,
this PR solves major issues on programming large applicaitons on an SAMD which are prepared for partial programming. At the end of such a programming session ETS is reading property 27 for each programmed table object, which is a CRC16citt of this table. Previous algorithm allocated an additional memory block in RAM for CRC calculation. 
Large applications (like my logicmodule) have a parameter block > 6k, the contained memcpy was overwriting other allocated memory.
This PR reads directly from provided buffer (i.e. flash) for CRC calculation, so it uses less RAM resources. Tests with both …

Get rid of occsional fails during ETS programming

---

src/stm32_platform.cpp

Addresses a side effect of https://github.com/thelsing/knx/pull/177, which causes the eeprom buffer to be overwritten every time getEepromBuffer is called. This prevented programming of STM32 boards as their initial bus address was lost before programming.

Fix stm32 eeprom handling

---

src/knx_facade.cpp
src/knx_facade.h
src/stm32_platform.cpp

Addressing https://github.com/thelsing/knx/discussions/206
A button press is now detected as _valid_ if it is longer than `PROG_BTN_PRESS_MIN_MILLIS` and shorter than `PROG_BTN_PRESS_MAX_MILLIS`. Each with reasonable defaults of 50ms and 500ms.
This removes the need for setting edge detection to RISING of FALLING. The interrupt will simply trigger on CHANGE.

Fix prog button handling

---

src/knx/dptconvert.cpp

This pull request just removes a print in dptconvert.cpp, which generates unexpected (and not understandable) output during debug sessions.
Regards, Waldemar

remove unnecessary print to console

---

src/knx/association_table_object.cpp
src/knx/association_table_object.h

- new prepareBinarySearch() called as soon as association_table changes
- fallback to linear search if ETS does not provide sorted ASAP entries
- activated with #define  BIN_SEARCH
This closes existing functionality gaps found after closing of #218. It was carefully testes on 4 different devices and seems to work as expected. I debugged the coding also taking some corner cases into account.
Please review and merge these changes.
Regards,
Waldemar

reimplemented binary search for translateAsap()

---

src/knx_facade.h

if not set otherwise, KNX_BUTTON is set to -1.
if the buttonPin is < 0, the isr for button handling is not attached, so the prog button handling in the stack will not be used.
Reason for this change:
There will be device without a physical prog button and prog mode is activated for example by touch sensor or display.
Currently the default to Pin 0 could lead to unpredicatbale results when the real Pin0 is floating.

make the Prog Button handling in the knx stack deativateable

---

src/knx/dpt.h
src/knx/dptconvert.cpp

correction for DPT 10.001 TimeOfDay  Dpt(10, 1) -> Dpt(10, 1, 1)
extension of dptconvert.cpp to get "tmp.tm_wday = weekDay;" decoded in Struct tm

correction for DPT 10.001 TimeOfDay and extension for day of week (tm_wday)

---

src/knx/application_layer.cpp
src/knx/application_layer.h
src/knx/bau.cpp
src/knx/bau.h
src/knx/bau_systemB.cpp
src/knx/bau_systemB.h
src/knx/knx_types.h
src/knx/platform.cpp
src/knx/platform.h

Added a callback for FunctionProperty.
Now we can use it in OGM-Common Modules so the ETS can communicate with the device (via Buttonscripts).
Also fixed the length.
(Request was always 1 byte to short, and Response 1 byte to long)

Added FunctionProperty Callback

---

src/knx/application_layer.cpp
src/knx/application_layer.h

This fix prevents a hanging situation in the stack. 
In rare cases it might happen, that confirm mesages are send before _savedAsapXXX is set. 
One of these rare cases: [this coding is entered](https://github.com/OpenKNX/knx/blob/10266a2966cb5923d8774199bb5b3bc6c756e3fa/src/knx/tpuart_data_link_layer.cpp#L455-L464), the sendBuffer contains an incorrect telegram and this leads to a send telegram with an ASAP = 0, which does not exist. 
This correction improves robustness and has no other side effects as far as I see. I tested it for more than 2 weeks in a productive system with thousands of telegrams. 
Please accept this pull request.

fix: prevent use of uninitialized _savedAsapXXX variables

---

src/knx/bau.h
src/knx/bau_systemB.cpp

Fix for a bug where the stack answers functionproperty even it is not handled by stack or callback.
-> Ended in a response with 64 zeros.

functionproperty respond only if handled

---

src/knx/application_layer.cpp

Hi,
this is a hotfix for my last fix-uniinitialized-asap. After further tests I realized, that an other - conceptual - problem in the stack does not allow to set _saveAsapXXX-Variables = 0 after processing. This fix is temparary, until the conceptual problem gets solved.
Please accept this pull request as soon as possible.
Regards,
Waldemar

Hotfix: remove of _savedAsapXXX = 0

---

src/knx/ip_data_link_layer.cpp
src/knx/ip_data_link_layer.h

instead of waiting 20ms after every telegram sent over ip to fullfill 50p/s sending limit, the sent telegram in the last 1000ms are counted.
If the limit is reached, packets are dropped (this is unlikely).
The limit "rolls" every 100ms and is recalculated.
This allows sending "bursts" that exceed 5p/100ms but do not exceed 50p/s (this is within knx spec).
This could be further improved by a tx queue. But in most cases there is no need for that.

Improve ip data link layer send limit

---

src/knx/tpuart_data_link_layer.cpp
src/knx/tpuart_data_link_layer.h

This PR fixes the problem where the function resetChip() blocks the whole core for 100ms.

fix: reset chip blocks

---

src/knx/tpuart_data_link_layer.cpp

This PR fixes the problem described in Issue #247 
This will block the core at startup for "RESET_TIMEOUT" (100ms).
Message "ERROR, TPUART not responding" will now only appear at startup if the TPUART is really not responding.
More detailed error messages (like letting now if tpuart is not responding after start) may included later.

fix #247 - TPUART Error Message

---

src/knx/application_layer.cpp
src/knx/tpuart_data_link_layer.cpp

This pull request addresses a Problem with ignored KNX-Telegrams in Hight-Load-Situations on the KNX-Bus. 
It does not change the default behaviour, but allows to set according defines outside of the project.
OVERRUN_COUNT limits the number of not processed bytes in UART buffer before telegrams are ignored. Default here is 7, on an RP2040 I got very good results with 31.
EOPR_TIMEOUT limits the time the processing of the address part of a telegram has. Default here is 8, on an RP2040 I got very good results with 32.
The other file (application_layer.cpp) was already part of the stack for some time, but produced many unnecessary mesages. My correction (removing the messages) also removed the _saveASAPxxx = 0; settings.
Please accept this pull request, as far as I can see here it has no …

Fix buffer overflow

---

src/knx/data_property.cpp

with start = 0 (read the number of current elements) and current elements = 0 (empty property) 0 was returned which results in an error message when reading this property.

fixed wrong answers to property read

---

src/knx/dptconvert.cpp

Writing DPT8.010 resulted in broken values as only one of bytes was used.

Fix: Conversion of DPT8.010 to Bus

---

src/knx/dptconvert.cpp

- all DPT9 numbers of the form (2^n)/100, n>10 (first value is 20.48) were converted to a payload of 0
- in other words: 20.48; 40.96; 81.92; etc. were send as 0!
Fix is tested and works fine. First time I got a bug report regarding this error was 3 years ago. At this time I couldn't reproduce...
Please merge this fix. Thanks. Waldemar

FIX: float16ToPayload

---

src/knx/application_layer.cpp
src/knx/application_layer.h
src/knx/bau27B0.cpp
src/knx/bau_systemB.cpp

- undo the first change because it was in the wrong place
- now really fixes the problem with the serial number handling

fixes the serial number handling

---

src/esp32_platform.cpp
src/esp32_platform.h
src/rp2040_arduino_platform.cpp
src/rp2040_arduino_platform.h

Allow to set the pins for the uart for RP2040 and ESP32. This feature is especially important for ESP32, because the pins has to be set in the Serial.begin method.

Allow to set uart pins for RP2040 and ESP32 platform

---

src/knx/ip_data_link_layer.cpp
src/knx/ip_parameter_object.cpp
src/knx/knx_ip_frame.h
src/knx_facade.cpp
src/knx_facade.h
src/rp2040_arduino_platform.cpp
src/rp2040_arduino_platform.h

this adds IP (WiFi and wired Ethernet) support to the rp2040 platform.
It includes also some optimizations for KNX-IP in general.
2. try, removed activitycallback and cleaned up logging

IP support for RP2040 plattform

---

src/knx/bau07B0.cpp
src/knx/bau07B0.h
src/knx/bau091A.cpp
src/knx/bau091A.h
src/knx/bau57B0.cpp
src/knx/bau57B0.h
src/knx/bits.h
src/knx/data_link_layer.cpp
src/knx/data_link_layer.h
src/knx/ip_data_link_layer.cpp
src/knx/ip_data_link_layer.h
src/knx/network_layer_entity.cpp
src/knx/network_layer_entity.h
src/knx/tpuart_data_link_layer.cpp
src/knx/tpuart_data_link_layer.h
src/knx_facade.h

Add the possibility to have a callback function signaling knx activity (for e.g. flashing LEDs)
Can be enabled with KNX_ACTIVITYCALLBACK

Add activity callback function

---

src/rp2040_arduino_platform.h

Again a build fail fix needed for the case that KNX_NETIF is not defined . Sorry!

Fix build error for missing variable if KNX_NETIF is not defined

---

src/knx/cemi_server.cpp
src/knx/data_link_layer.cpp

I want to use "knx-usb" example on ESP32 platform. And I noticed a problem.
Build for example "knx-usb" will failed if define 'USE_CEMI_SERVER' without 'USE_RF', such as ESP32. This commit only solve the build error, by add preprocessor to check if USE_RF is defined. Tested on following env:
`[env:adafruit_qtpy_esp32s3_n4r2]`
`platform = espressif32`
`board = adafruit_qtpy_esp32s3_n4r2`
`framework = arduino`
`lib_extra_dirs = ../../../`
`extra_scripts = pre:custom_hwids.py`
`board_build.usb_product = "KNX RF - USB Interface"`
`lib_deps = `
`	knx`
`	adafruit/Adafruit TinyUSB Library@^3.2.0`
`build_flags = `
`	-DUSE_USB`
`	-DUSE_TINYUSB`
`	-Wno-unknown-pragmas`
`	-DMASK_VERSION=0x07B0`

Fix: build for cemi_server on platform without RF support will failed

---

src/knx/group_object.cpp
src/knx/group_object.h

The differentiation between uninitialized and initialized state can NOT be represented correctly in ComFlag alone:
> it might be in state Transmitting during a ReadRequest on startup while value is still not valid
Add a separate uninitialized flag to overcome the limitations of ComFlag.
* We use MSB to store uninitialized state and keep the size of GroupObject the same saving memory resources.
* The old uninitialized handling is not changed for compatibility reasons.

Fix: Group-Object `_commFlag != Uninitialized` does NOT Guarantee an Actual Initialization

---

src/knx/group_object.cpp

ESP8266 crashed when receiving write requests on group objects of type DPT2 or DPT3 with less than 1 byte in size.

Fix crash for DPTs with less than 1byte in size

---

src/knx/dptconvert.cpp

Return DPT2 and DPT3 as uint8_t and let the application handle the different bits.

handle DPT2 and DPT3 as uint8_t in code

---

src/knx_facade.cpp

ICACHE_RAM_ATTR is deprecated in the latest ESP8266 core versions and will lead to a compilation warning. IRAM_ATTR should be used instead.

Fix ESP compiler warning

---

src/knx_facade.h

Allow disabling ProgLED by setting _ledPin=-1
For use cases where all GPIOs are in use or LED_BUILTIN pin is used for other functionality.

Don't assign built-in LED as ProgLED by default

---

.github/workflows/platform-io.yml

The GitHub-action 'PlatformIO CI' fails as python package "intelhex" is missing
Install the missing package

Fix Action 'PlatformIO CI': Install "intelhex"

---

src/knx/memory.cpp

Unload-Timeout was introduced with #316 
`_savedTimeout==0` is defined as no timeout running. Prevent setting to `0` in the rare case `millis()==0`.

Fix for PR #316: Special Case Handling for Unload-Timeout

---

examples/knx-demo-esp-idf/main/main.cpp
src/esp32_idf_platform.cpp
src/esp32_idf_platform.h

Last commit I fixed speed 19200 baud, this commit solve it.

Support configure UART speed for ESP IDF
